### ISSUE TITLE
Redisでrankingを実装する

### ISSUE THREAD

**Issue by dictav** [vortispy/Doya#1]
Redisにはランキングにピッタリの zscore という形式がある。
scoreの値を操作する `ZINCRBY key increment member` というコマンドでランキングを実装できる。

key を image_ranking とすれば以下のようにランク付けできる。（image_url3が最もrankが上）

```
redis> ZINCRBY image_ranking 1 image_url1
redis> ZINCRBY image_ranking 5 image_url2
redis> ZINCRBY image_ranking 100 image_url3
```

これを取ってくるには以下のようにする。

```
redis> ZREVRANGEBYSCORE image_ranking -inf +inf WITHSCORES LIMIT 0 10
```

これで、スコアの高い方から10個までのアイテムをスコア付きで取得できる。

**Comment by vortispy** [comment]
とりあえず実装しました。「Ranking」ボタンを押すと表示されます。
困った点など
・ネットワーク通信を別スレッドで実行させるために毎回AsyncTask使うの面倒。ほかの方法も考える。
・ZADDやZINCRBYで作った値をGETできない(たぶん)。そのため別に値を作っておかなくてはいけない
・もろもろの処理が今のままだと新しいデータを追加するのは難しいので考えておく
・俺のJAVA能力が低すぎてIDEに介護されながら書いてる

**Comment by dictav** [comment]
> ネットワーク通信を別スレッドで実行させるために毎回AsyncTask使うの面倒。ほかの方法も考える。

これはそういうものなので仕方ない。AndroidAnnotation 使うと楽になる。

> ZADDやZINCRBYで作った値をGETできない(たぶん)。

GETでは取得できない。`ZREVRANGEBYSCORE` を使う必要がある。意味違う？
