### ISSUE TITLE
Refactoring案

### ISSUE THREAD

**Issue by dictav** [vortispy/Doya#14]
## DoyaRankItemAdapter.S3GetImage は不要じゃないか？

S3のデータはURLで参照できるので S3 を直接叩く必要はないんじゃないか？
## DoyaRankItemAdapter.getView は重いんじゃないか？

getView() は描画される度に呼び出されるメソッドなので、その中に通信処理を埋め込むのは重いと思う。特に Jedis に関してはコンスタントラクタで一度に読み込めば良いのでそちらに移すべきじゃないか？

**Comment by vortispy** [comment]
> S3のデータはURLで参照できる

そうだったのか

DoyaItemAdapter, DoyaRankItemAdapterともにgetView重いので修正した方がいいですね。
初回描画時に通信してDoyaData.setImageDataをつかってデータを保持するようにします。

> 特に Jedis に関してはコンスタントラクタで一度に読み込めば良いのでそちらに移すべきじゃないか？

ソースコード見たらRankingFragmentでランキングを取得してるのでそもそもDoyaRankItemAdapter.JedisGetRankは不要そうです。

**Comment by dictav** [comment]
> > S3のデータはURLで参照できる
> 
> そうだったのか

URL はこんな感じ
https://s3-ap-northeast-1.amazonaws.com/doya/pictures/1.jpg
