### ISSUE TITLE
ブログを書く

### ISSUE THREAD

**Issue by dictav** [vortispy/Doya#16]
今回のアプリを作成して勉強になったことをまとめる。
- 忘れないように大事なことはメモる
- 分からなかった部分は調べる（質問する）
- 改善すべき点を version2.0 の issueに追加する（https://github.com/vortispy/Doya/milestones/version%202.0）
- 次のアプリの案を考える

**Comment by vortispy** [comment]
http://vortispy.hatenablog.com/entry/2014/08/14/020438
